project:
  type: book
  output-dir: docs

book:
  title: "R for Novice Programmers (1e)"
  subtitle: "First Steps with R and RStudio"
  image: Cover_R4NP.png
  author: William Okech
  date: 01/01/2024
  reader-mode: true

  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-9WD4X1TR0R"
    anonymize-ip: true

  page-footer:
    left: |
      R for Novice Programmers (1e) was written by William Okech.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: Cover_R4NP.png
  favicon: Cover_R4NP.png
  #site-url: 
  repo-url: https://github.com/wokech/r4novice
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd

    - overview.qmd
    - download_install.qmd
    - navigating.qmd
    - managing.qmd
    - importing.qmd
    - arithmetic_variables.qmd
    - operators.qmd
    - data_types.qmd
    - vectors.qmd
    - data_struct_1.qmd
    - data_struct_2.qmd
    - missing.qmd
    - conclusion.qmd
    - references.qmd
  appendices:
    - appendix.qmd
    - datasets.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
  pdf:
    documentclass: scrreprt

editor: visual

