# Conclusion {.unnumbered}

**We have finally come to the end of the “R for Novice Programmers” book. Congratulations on completing this learning journey!**

The overall goal of this book was to introduce non-programmers or those with very little programming experience to R and RStudio and their use in basic statistical programming. It is hoped that the learners gained new skills and discovered how this software could be used to simplify everyday tasks in their workplaces. The learner should now be able to understand all the topics listed below based on the previously described learning objectives.

| Chapter | Title                                                 | Date Completed |
|:-------------|:-------------------------------------------|:-------------|
|         | Introduction                                          |                |
| 1       | Overview of R and RStudio                             |                |
| 2       | Download and Install R and RStudio                    |                |
| 3       | Navigating the R and RStudio interfaces               |                |
| 4       | Managing your files and data                          |                |
| 5       | Importing data and saving analysis outputs            |                |
| 6       | Basic arithmetic, arithmetic operators, and variables |                |
| 7       | The primary types of operators in R                   |                |
| 8       | Data Types                                            |                |
| 9       | Vectors                                               |                |
| 10      | Data Structures (Part I)                              |                |
| 11      | Data Structures (Part II)                             |                |
| 12      | Handling missing data                                 |                |
|         | Conclusion                                            |                |
|         | Appendix                                              |                |

: Syllabus {# tbl-syllabus .striped .hover tbl-colwidths="\[5, 80, 15\]"}

To maintain mastery of the course material, the learner is encouraged to practice consistently, explore freely available resources, get involved in real-world projects, and work with the large R community. In future sessions, the learner will focus on specific topics such as data wrangling/manipulation, data visualization, and programming. Therefore, I would encourage the learner to review some of the links I have provided in the Appendix and look out for more books in the future which will cover:

i.  Data visualization

ii. Tidyverse

iii. Programming: Functions, Loops, and Control Statements

iv. Data Science

v.  Statistics

vi. Machine Learning and Artificial Intelligence

vii. Publishing with R Markdown and/or Quarto

viii. R Shiny

**Thanks for your participation and for completing this book!**
