# Introduction {.unnumbered}

## Why did I write this book?

This book is primarily intended to cater to the needs of individuals who have a desire to learn the basics of programming. I focus on R and RStudio because their capabilities may be relevant to a wide variety of individuals and organizations seeking to perform basic statistical analysis and data visualization. Personally, my skills in R and RStudio were gained via classroom instruction, online tutorials and videos, as well as relevant blog posts. A significant disadvantage of some of these resources is the assumption of prior programming knowledge. To address this, I begin the book with instructions for downloading software, navigating the R and RStudio interfaces, and an overview of the basics of R to decrease the cognitive load on novices.

## About the author

The author of this book is a Certified Carpentries instructor and a trainer with the Digital Research Academy. Additionally, the author holds a PhD in Biomedical Engineering and has completed postdoctoral fellowships in vascular biology and infectious diseases. Lastly, the author is passionate about using R and RStudio to generate data-driven visualizations to allow for a deeper understanding of public policy issues.

## Syllabus

At the end of the book, the student should be able to perform the tasks listed in the syllabus below.

| Chapter | Title                                                 | Date Completed |
|:--------|:------------------------------------------------------|:---------------|
|         | Introduction                                          |                |
| 1       | Overview of R and RStudio                             |                |
| 2       | Download and Install R and RStudio                    |                |
| 3       | Navigating the R and RStudio interfaces               |                |
| 4       | Managing your files and data                          |                |
| 5       | Importing data and saving analysis outputs            |                |
| 6       | Basic arithmetic, arithmetic operators, and variables |                |
| 7       | The primary types of operators in R                   |                |
| 8       | Data Types                                            |                |
| 9       | Vectors                                               |                |
| 10      | Data Structures (Part I)                              |                |
| 11      | Data Structures (Part II)                             |                |
| 12      | Handling missing data                                 |                |
|         | Conclusion                                            |                |
|         | Appendix                                              |                |

: Syllabus {# tbl-syllabus .striped .hover tbl-colwidths="\[5, 75, 20\]"}

## Sample chapter design

Each lesson will follow a pre-described format

i.  Questions to be addressed

ii. Learning objectives

iii. Lesson content

iv. Practice exercises

v.  Lesson summary

The learners are encouraged to work through each chapter sequentially. For each chapter, the learner should first review the questions to be addressed and learning objectives. Next, the student should read through the lesson content and ensure that the questions and learning objectives sections have been addressed. Finally, the learners should do the practice exercises to reinforce the newly learned concepts and review the lesson summary.

## Feedback

Feedback can be provided using the following channels:

i.  Email: willyokech\@gmail.com

ii. Github pull request: [Link](https://github.com/wokech/r4novice)

## Summary

Overall, I believe that this book will increase both the knowledge and confidence levels of novice programmers and allow them to perform basic statistical analysis and simplify everyday computational tasks at home or in their workplaces. In the next chapter, I will provide a basic overview of the R and RStudio ecosystem.
